# Generated by Django 3.2 on 2021-04-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='page_number',
        ),
        migrations.RemoveField(
            model_name='source',
            name='video_time_stamp',
        ),
        migrations.AddField(
            model_name='term',
            name='ref_point',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
