# Generated by Django 3.2 on 2021-04-19 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210413_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='term',
            name='ref_point',
        ),
        migrations.RemoveField(
            model_name='term',
            name='source',
        ),
        migrations.AddField(
            model_name='source',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='ref_point',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.term'),
        ),
    ]
