# Generated by Django 3.2 on 2021-04-19 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210419_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='source',
            name='ref_point',
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.TextField(blank=True, null=True)),
                ('ref_point', models.IntegerField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.source')),
            ],
        ),
    ]
