# Generated by Django 3.2 on 2021-04-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210419_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='term',
        ),
        migrations.AddField(
            model_name='source',
            name='term',
            field=models.ManyToManyField(to='posts.Term'),
        ),
    ]
