# Generated by Django 3.2 on 2021-04-19 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210419_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='definition',
            name='term',
        ),
        migrations.AddField(
            model_name='definition',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.term'),
        ),
    ]
