# Generated by Django 3.2 on 2021-04-22 12:18

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210419_0939'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='source',
            managers=[
                ('sources', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='term',
            managers=[
                ('terms', django.db.models.manager.Manager()),
            ],
        ),
    ]
