# Generated by Django 3.2 on 2021-04-22 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20210422_0818'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='source',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='term',
            managers=[
            ],
        ),
    ]
